advert_index:
    path:     /
    defaults: { _controller: "ApiAdvertBundle:Advert:index" }
    methods:  GET

advert_show:
    path:     /{slug}/show
    defaults: { _controller: "ApiAdvertBundle:Advert:show" }
    methods:  GET

advert_new:
    path:     /new
    defaults: { _controller: "ApiAdvertBundle:Advert:new" }
    methods:  [GET, POST]

advert_edit:
    path:     /{id}/edit
    defaults: { _controller: "ApiAdvertBundle:Advert:edit" }
    methods:  [GET, POST]

advert_delete:
    path:     /{id}/delete
    defaults: { _controller: "ApiAdvertBundle:Advert:delete" }
    methods:  [DELETE]

advert_category:
    path:     /list-advert-category/{category}
    defaults: { _controller: "ApiAdvertBundle:Advert:advertCategory" }

advert_city:
    path:     /list-advert-city/{city}
    defaults: { _controller: "ApiAdvertBundle:Advert:advertCity" }

advert_city_category:
    path:     /list-advert/{city}/{category}
    defaults: { _controller: "ApiAdvertBundle:Advert:advertCityCategory" }