api_advert_homepage:
    path: /
    defaults: { _controller: ApiAdvertBundle:Default:index }

api_advert_category:
    resource: "@ApiAdvertBundle/Resources/config/routing/category.yml"
    prefix:   /category

api_advert_advert:
    resource: "@ApiAdvertBundle/Resources/config/routing/advert.yml"
    prefix:   /advert

api_advert_city:
    resource: "@ApiAdvertBundle/Resources/config/routing/city.yml"
    prefix:   /city

api_advert_api:
    resource: "@ApiAdvertBundle/Resources/config/routing/api.yml"
    prefix:   /api