<?php

namespace Api\AdvertBundle\Repository;

use Api\AdvertBundle\Entity\Category;

/**
 * AdvertRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class AdvertRepository extends \Doctrine\ORM\EntityRepository
{
    public function findAdverts()
    {
        $date = new \DateTime();
        $date->modify('-10 day');

        $qb = $this->createQueryBuilder('a');

        $qb->where('a.date > :date')
            ->setParameter(':date', $date)
            ->orderBy('a.date', 'DESC')
            ->setMaxResults(5);
        5;

        return $qb
            ->getQuery()
            ->getResult()
            ;
    }

    public function findAdvertCategory($category, $page = 1, $limit = 0)
    {
        $date = new \DateTime();
        $date->modify('-10 day');

        $qb = $this->createQueryBuilder('a');

        $qb
            ->innerJoin('a.categories', 'cat')
            ->addSelect('cat')
            ->where('cat.slugCat = :category')
            ->andWhere('a.date > :date')
            ->setParameters(array('date' => $date, 'category' => $category))
            ->setFirstResult(($page-1)*$limit)
            ->orderBy('a.date', 'DESC');

        if($limit > 0 ){
            $qb = $qb->setMaxResults($limit);
        }


        return $qb
            ->getQuery()
            ->getResult()
            ;
    }

    public function findAdvertCity($city, $page = 1, $limit = 0)
    {
        $date = new \DateTime();
        $date->modify('-10 day');

        $qb = $this->createQueryBuilder('a');

        $qb
            ->innerJoin('a.city', 'city')
            ->addSelect('city')
            ->where('city.name = :city')
            ->andWhere('a.date > :date')
            ->setParameters(array('date' => $date, 'city' => $city))
            ->setFirstResult(($page-1)*$limit)
            ->orderBy('a.date', 'DESC');

        if($limit > 0 ){
            $qb = $qb->setMaxResults($limit);
        }

        return $qb
            ->getQuery()
            ->getResult()
            ;
    }

    public function findAdvertCityCategory($city, $category, $page = 1, $limit = 0)
    {
        $date = new \DateTime();
        $date->modify('-10 day');

        $qb = $this->createQueryBuilder('a');

        $qb
            ->innerJoin('a.city', 'city')
            ->addSelect('city')
            ->innerJoin('a.categories', 'cat')
            ->addSelect('cat')
            ->where('city.name = :city')
            ->andWhere('cat.slugCat = :category')
            ->andWhere('a.date > :date')
            ->setParameters(array('date' => $date, 'city' => $city, 'category' => $category))
            ->setFirstResult(($page-1)*$limit)
            ->orderBy('a.date', 'DESC');

        if($limit > 0 ){
            $qb = $qb->setMaxResults($limit);
        }

        return $qb
            ->getQuery()
            ->getResult()
            ;
    }
}
